export type Question = {
  id: string;
  text: string;
  category: 'fun' | 'romantic' | 'deep' | 'practical';
};

export const questions: Question[] = [
  // Fun Questions (Pastel Yellow)
  { id: 'f1', text: "Pineapple belongs on pizza", category: "fun" },
  { id: 'f2', text: "Camping is better than staying in a hotel", category: "fun" },
  { id: 'f3', text: "Board games are more fun than video games", category: "fun" },
  { id: 'f4', text: "Dancing in the rain is romantic", category: "fun" },
  { id: 'f5', text: "Karaoke nights should be a monthly tradition", category: "fun" },
  { id: 'f6', text: "Morning people are better than night owls", category: "fun" },
  { id: 'f7', text: "Beach vacations are better than city trips", category: "fun" },
  { id: 'f8', text: "Ice cream is a valid breakfast food", category: "fun" },
  { id: 'f9', text: "Reality TV shows are genuinely entertaining", category: "fun" },
  { id: 'f10', text: "Dogs are better pets than cats", category: "fun" },
  { id: 'f11', text: "Breakfast for dinner is better than dinner for breakfast", category: "fun" },
  { id: 'f12', text: "Travel vlogs are better than movie nights", category: "fun" },
  { id: 'f13', text: "Trying new restaurants is better than cooking at home", category: "fun" },
  { id: 'f14', text: "Weekend getaways are better than long vacations", category: "fun" },
  { id: 'f15', text: "Game nights should be a weekly tradition", category: "fun" },
  { id: 'f16', text: "Spontaneous plans are better than scheduled ones", category: "fun" },
  { id: 'f17', text: "Picnics are more romantic than restaurant dates", category: "fun" },
  { id: 'f18', text: "Road trips are better than flying", category: "fun" },
  { id: 'f19', text: "Taking photos ruins the moment", category: "fun" },
  { id: 'f20', text: "Couple&apos;s costumes are fun", category: "fun" },
  { id: 'f21', text: "Indoor dates are better than outdoor activities", category: "fun" },
  { id: 'f22', text: "Museums are interesting date spots", category: "fun" },
  { id: 'f23', text: "Couple workouts are fun", category: "fun" },
  { id: 'f24', text: "Double dates are better than solo dates", category: "fun" },
  { id: 'f25', text: "Learning a new hobby together is fun", category: "fun" },
  { id: 'f26', text: "Couple&apos;s spa days are worth it", category: "fun" },
  { id: 'f27', text: "Cooking together is better than ordering in", category: "fun" },
  { id: 'f28', text: "Watching shows together is quality time", category: "fun" },
  { id: 'f29', text: "Social media challenges as couples are fun", category: "fun" },
  { id: 'f30', text: "Holiday traditions are important", category: "fun" },

  // Romantic Questions (Pastel Pink)
  { id: 'r1', text: "Love at first sight exists", category: "romantic" },
  { id: 'r2', text: "Surprise dates are the best dates", category: "romantic" },
  { id: 'r3', text: "Long-distance relationships can work", category: "romantic" },
  { id: 'r4', text: "Public displays of affection are sweet", category: "romantic" },
  { id: 'r5', text: "Romantic movies reflect real relationships", category: "romantic" },
  { id: 'r6', text: "Valentines Day is important", category: "romantic" },
  { id: 'r7', text: "Date nights should be weekly", category: "romantic" },
  { id: 'r8', text: "Love letters are better than text messages", category: "romantic" },
  { id: 'r9', text: "Small gestures matter more than grand ones", category: "romantic" },
  { id: 'r10', text: "Couples should have nicknames for each other", category: "romantic" },
  { id: 'r11', text: "Romantic gestures should be spontaneous", category: "romantic" },
  { id: 'r12', text: "Distance makes the heart grow fonder", category: "romantic" },
  { id: 'r13', text: "Celebrating monthsaries is important", category: "romantic" },
  { id: 'r14', text: "Romance needs planning and effort", category: "romantic" },
  { id: 'r15', text: "Handmade gifts are more meaningful", category: "romantic" },
  { id: 'r16', text: "Partners should express love daily", category: "romantic" },
  { id: 'r17', text: "Social media posts about love are sweet", category: "romantic" },
  { id: 'r18', text: "Pet names are essential in relationships", category: "romantic" },
  { id: 'r19', text: "Keeping the spark alive requires effort", category: "romantic" },
  { id: 'r20', text: "Romance changes with time", category: "romantic" },
  { id: 'r21', text: "Grand gestures are overrated", category: "romantic" },
  { id: 'r22', text: "Digital love letters count", category: "romantic" },
  { id: 'r23', text: "Every date should have romance", category: "romantic" },
  { id: 'r24', text: "Partners should flirt regularly", category: "romantic" },
  { id: 'r25', text: "Recreating first dates is romantic", category: "romantic" },
  { id: 'r26', text: "Romance needs mystery", category: "romantic" },
  { id: 'r27', text: "Romantic movies set unrealistic expectations", category: "romantic" },
  { id: 'r28', text: "Physical touch is essential for romance", category: "romantic" },
  { id: 'r29', text: "Romance requires creativity", category: "romantic" },
  { id: 'r30', text: "Romantic gestures should be personal", category: "romantic" },

  // Deep Questions (Pastel Blue)
  { id: 'd1', text: "Social media affects relationships negatively", category: "deep" },
  { id: 'd2', text: "Past relationships shape current ones", category: "deep" },
  { id: 'd3', text: "Marriage is necessary for commitment", category: "deep" },
  { id: 'd4', text: "Having children changes relationships", category: "deep" },
  { id: 'd5', text: "Religion matters in relationships", category: "deep" },
  { id: 'd6', text: "Politics affect relationships", category: "deep" },
  { id: 'd7', text: "Trust needs to be earned", category: "deep" },
  { id: 'd8', text: "People can change for love", category: "deep" },
  { id: 'd9', text: "Compromise is key to relationships", category: "deep" },
  { id: 'd10', text: "Communication solves most problems", category: "deep" },
  { id: 'd11', text: "Shared values are more important than shared interests", category: "deep" },
  { id: 'd12', text: "Relationships require constant growth", category: "deep" },
  { id: 'd13', text: "Individual identity matters in relationships", category: "deep" },
  { id: 'd14', text: "Age gap matters in relationships", category: "deep" },
  { id: 'd15', text: "Opposite personalities complement each other", category: "deep" },
  { id: 'd16', text: "Partners should share friend groups", category: "deep" },
  { id: 'd17', text: "Mental health affects relationships", category: "deep" },
  { id: 'd18', text: "Relationship roles should be defined", category: "deep" },
  { id: 'd19', text: "Love languages evolve over time", category: "deep" },
  { id: 'd20', text: "Emotional intimacy requires vulnerability", category: "deep" },
  { id: 'd21', text: "Past trauma needs to be discussed", category: "deep" },
  { id: 'd22', text: "Self-love comes before relationship love", category: "deep" },
  { id: 'd23', text: "Boundaries strengthen relationships", category: "deep" },
  { id: 'd24', text: "Expectations should be communicated", category: "deep" },
  { id: 'd25', text: "Relationship goals need alignment", category: "deep" },
  { id: 'd26', text: "Support systems outside relationships matter", category: "deep" },
  { id: 'd27', text: "Cultural differences impact relationships", category: "deep" },
  { id: 'd28', text: "Forgiveness is a choice", category: "deep" },
  { id: 'd29', text: "Relationships need emotional work", category: "deep" },
  { id: 'd30', text: "Long-term compatibility requires effort", category: "deep" },

  // Practical Questions (Pastel Purple)
  { id: 'p1', text: "Joint bank accounts are necessary", category: "practical" },
  { id: 'p2', text: "Living together before marriage is important", category: "practical" },
  { id: 'p3', text: "Splitting bills 50/50 is fair", category: "practical" },
  { id: 'p4', text: "Shared passwords show trust", category: "practical" },
  { id: 'p5', text: "Regular budget discussions are necessary", category: "practical" },
  { id: 'p6', text: "Housework should be shared equally", category: "practical" },
  { id: 'p7', text: "Career should come before relationship", category: "practical" },
  { id: 'p8', text: "Saving for the future is essential", category: "practical" },
  { id: 'p9', text: "Prenuptial agreements are important", category: "practical" },
  { id: 'p10', text: "Both partners should work", category: "practical" },
  { id: 'p11', text: "Financial goals should align", category: "practical" },
  { id: 'p12', text: "Phone passwords should be shared", category: "practical" },
  { id: 'p13', text: "Chores should be assigned", category: "practical" },
  { id: 'p14', text: "Regular relationship check-ins are needed", category: "practical" },
  { id: 'p15', text: "In-laws boundaries are important", category: "practical" },
  { id: 'p16', text: "Lifestyle habits should match", category: "practical" },
  { id: 'p17', text: "Career sacrifices should be discussed", category: "practical" },
  { id: 'p18', text: "Location choices need agreement", category: "practical" },
  { id: 'p19', text: "Shared calendars are necessary", category: "practical" },
  { id: 'p20', text: "Holiday plans need compromise", category: "practical" },
  { id: 'p21', text: "Health decisions affect both partners", category: "practical" },
  { id: 'p22', text: "Pet responsibilities should be shared", category: "practical" },
  { id: 'p23', text: "Social media boundaries matter", category: "practical" },
  { id: 'p24', text: "Investment decisions should be joint", category: "practical" },
  { id: 'p25', text: "Time management needs discussion", category: "practical" },
  { id: 'p26', text: "Household rules need agreement", category: "practical" },
  { id: 'p27', text: "Future planning should be mutual", category: "practical" },
  { id: 'p28', text: "Personal space needs definition", category: "practical" },
  { id: 'p29', text: "Conflict resolution methods matter", category: "practical" },
  { id: 'p30', text: "Family planning requires agreement", category: "practical" }
];